### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by montuIO** [TrillCyborg/onefraction#13]
When I run yarn start I get this error message. Trying to run this on the latest MacOS

Failed to compile
./src/utils/env.ts
Module not found: Can't resolve '../config/development.env.json' in '/Users/username/Desktop/onefraction/client/src/utils'
This error occurred during the build time and cannot be dismissed.

**Comment by Googlewasmyidea** [comment]
Perhaps the name change from onefraction/client/src/config/example.env.json to onefraction/client/src/config/development.env.json will do it? Let me know.

**Comment by montuIO** [comment]
That makes sense now. Sorry I'm new to programming trying to learn it through open source projects.
